#!/bin/bash
# WRF Information Script

echo "========================================"
echo "WRF/WPS Docker Container Information"
echo "========================================"
echo ""
echo "WRF Installation Directory: $WRF_DIR"
echo "WPS Installation Directory: $WPS_DIR"
echo ""
echo "Available WRF executables:"
ls -la $WRF_DIR/main/*.exe 2>/dev/null || echo "No WRF executables found"
echo ""
echo "Available WPS executables:"
ls -la $WPS_DIR/*.exe 2>/dev/null || echo "No WPS executables found"
echo ""
echo "Environment Variables:"
echo "  NETCDF=$NETCDF"
echo "  HDF5=$HDF5"
echo "  JASPERLIB=$JASPERLIB"
echo "  JASPERINC=$JASPERINC"
echo ""
echo "Quick Start Commands:"
echo "  WPS: cd $WPS_DIR && ./geogrid.exe && ./ungrib.exe && ./metgrid.exe"
echo "  WRF: cd $WRF_DIR/run && mpirun -np [num_processors] ./wrf.exe"
echo ""
echo "Use 'run.sh' for simplified execution:"
echo "  run.sh wps              - Run all WPS components"
echo "  run.sh wrf [nproc]      - Run WRF with specified processors"
echo "  run.sh real [nproc]     - Run real.exe"
echo "========================================"
